name: Docker Image Release Pipeline

on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
    PADISAH: Osman
    IMAGE_NAME: phptodo-example
    IMAGE_TAG: latest
    
jobs:
    docker-img-build-job:
        env:
            PADISAH2: Orhan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: pwd && ls -al
              env:
                PADISAH3: Murad
    docker-push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                echo $PADISAH
                echo $PADISAH2
                echo $PADISAH3

            # - run: docker image build -t ugurkontel/phptodo-example:frontend -f ./Dockerfile.frontend
            # - run: docker image build -t ugurkontel/phptodo-example:backend -f ./Dockerfile.backend
            # - run: docker image build -t ugurkontel/phptodo-example:database -f ./Dockerfile.database

            # - run: docker login -u ugurkontel -p P@ssw0rd!

            # - run: docker push ugurkontel/phptodo-example:frontend
            # - run: docker push ugurkontel/phptodo-example:backend
            # - run: docker push ugurkontel/phptodo-example:database