name: Ilk Test Pipeline

on:
    push:
        branches:
            - main
    workflow_dispatch:
    
jobs:
    artifacts_deneme_job:
      runs-on: ubuntu-latest
      steps:
        - name: Hello
          run: echo "Hello World!"
        
        - name: Dosya Oluşturma
          run: echo "Hello World!" > hello.txt

        - name: Dosyayi Check Etme
          run: cat hello.txt
      