name: Ilk Test Pipeline

on:
    push:
        branches:
            - main
    workflow_dispatch:
    
jobs:
    artifacts-deneme-job:
      runs-on: ubuntu-latest
      steps:
        - name: Hello
          run: echo "Hello World!"
        
        - name: Dosya Oluşturma
          run: echo "Hello World!" > hello.txt

        - name: Dosyayi Check Etme
          run: cat hello.txt
      
        - name: Artifacts Upload
          uses: actions/upload-artifact@v4
          with:
            name: code-coverage-report
            path: hello.txt

    artifacts-deneme2-job:
      needs: artifacts-deneme-job
      runs-on: ubuntu-latest
      steps:
        - name: Artifacts Download
          uses: actions/download-artifact@v4
          with:
            name: code-coverage-report
            path: .

        - name: Dosyayi Check Etme
          run: ls -al